bin/tests/index.html, bin/tests/test.js
Hi pburtchaell, 
I was trying this great component directly opening the bin/tests/index.html file in the browser from fileystem and it not loaded.
=> test.js path when the test is launched from filesystem.

src/notification.js
Thought I'd check this in because it's a tiny fix and it was my bad to start! Basically just sorts out the issues discussed in this PR https://github.com/pburtchaell/react-notification/pull/15 and issue #14.
=> Dismiss timeout passes correct function. Fixes #14

bin/tests/test.js, src/notification.js
I moved the timeout codes to render so that the timer will use dismissAfter value correctly.
=> fix Dismiss timeout to work properly with props passing

Makefile, README.md, examples/es2015/index.js, package.json, src/notification.js, test/notification.js
=> Add support for React version 0.14.0

examples/es2015/index.js, src/notificationList.js, src/stackableNotification.js
sorry, no tests. I'm on Windows and can't get the test script to run.
Being on Windows, I had to change the start script to     "start": "set NODE_ENV=development && node webpack.local.server.js",
Also, the webpack server was choking because there was no "mount" element on the page. This was remedied by adding some markup to examples/es2015/index.html and adding the following to webpack.local.config.js
line 34:
new HtmlWebpackPlugin({
title: 'example',
template: './examples/es2015/index.html',
inject: 'body'
}),
I did not push this because I realize I just may be missing something.
=> Notifications list

src/notificationStack.js, test/notification.js
Hi! I've fixed this issue: https://github.com/pburtchaell/react-notification/issues/43
=> Fix DismissAfter hardcoded in notification stack.

README.md, examples/single-notification/index.js, src/defaultPropTypes.js, src/notification.js, test/mockNotification.js, test/notification.js
Added title option to the notification.
Started using this project and really missed the option to add a title to the notification.
=> Added title option

README.md, examples/notification-tree/index.js, package.json
- Update README with new example code for Stacked Notifications and disclaimers.
- Remove `immutable.js` since it's currently not used.
=> Update Readme and Stack Example

README.md, src/notificationStack.js, src/stackedNotification.js, test/notificationStack.js
Adds the ability to pass in a function for either `barStyle` or `activeBarStyle` props on the NotificationStack component. This makes the bottom css value controllable by the user.
Resolves #57.
Resolves #77.
=> Dynamically control bar bottom value

src/notification.js
Hi!
I use react-notification in my current project.
I think - it's a great job!
But I realized that it's not working for IE9. 
This small change in the code fixes setting the dismissTimeout for slow browsers.
Greetings!
=> fix constructor for slow browsers

.babelrc, package.json
closes #85 
@pouu69 Would you have some time to test if this solves your issue?
ping @pburtchaell
=> Fix(babel): Make babel polyfill Object.assign

.gitignore, Makefile, README.md, src/defaultPropTypes.js, src/notification.js, src/stackedNotification.js, test/notification.js, test/notificationStack.js, test/setup.js
@pburtchaell Need this now, so tossing up this PR with the changes cp added.
=> Disable timeout

README.md, src/stackedNotification.js, test/notificationStack.js
=> Pass function for deactivating notification to onClick handler to stackedNotification

docs/guides/props.md, src/defaultPropTypes.js
Noticed the `titleStyle` prop was missing from the docs - great work on this library!
=> Add titleStyle to PropTypes and docs

test/notificationStack.js
Find out, that there was a test, that didn't work as expected.
=> notificationStack: test fix

docs/guides/styles.md, src/notificationStack.js, test/notificationStack.js
Trying to solve the [issue](https://github.com/pburtchaell/react-notification/issues/117). `notification` paramenter added to `barStyleFactory` and `activeBarStyleFactory`.
I've added it as a third parameter, in order not to break existing functionality.
Resolves #117.
=> Bar styles factories enhancement

.travis.yml
Fixes build issues with JSDOM 11
=> build(travis.yaml): Use node 6

examples/webpack.config.js, package.json, yarn.lock
=> Upgrade to webpack 2

.eslintrc, .gitattributes
=> Remove line break rule from ESLint

.travis.yml, README.md, package-lock.json, package.json, yarn.lock
Changes:
- Updates Node version for Travis CI
- Updates dependencies
- Adds `postinstall` script to keep yarn.lock and package-lock.json in sync
=> Update Dependencies and Travis CI

index.d.ts
Hello! :wave: 
This template enables you to open an issue that is valuable for you, the project, and the GitHub community. :two_hearts:
Before submitting an issue, please:
1. Agree the [Code of Conduct](/.github/CODE_OF_CONDUCT.md).
2. Read the [Contributing Guide](/.github/CONTRIBUTING.md).
If you are new to open source, check out this 38 minute course on [how to contribute to open source on GitHub](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github). It's free! :smile:
---
Before submitting a pull request, please make sure the following is done:
1. Add tests for new functionality or bug fixes, following the [red/green/refactor method](https://en.wikipedia.org/wiki/Test-driven_development#Development_style)
2. Ensure all tests pass: `npm test`
3. Update …
=> Add onClick prop to NotificationStack definition

package-lock.json, package.json
=> Release Version 6.8.4

src/notificationStack.js
=> fix(NotificationStack): set action proptype from default proptypes
